<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 4/3/2015
 * Time: 1:26 PM
 */

namespace common\modules\routing\widgets\graphhopper;


use yii\base\Exception;
use yii\base\Widget;
use yii\helpers\Json;
use yii\web\View;

class RoutingWidget extends Widget{
    public $mapDivId;
    public $userLocationDivId;
    public $containerId;
    public $ghAssetBaseUrl;
    public $widgetAssetBaseUrl;

    public $clientOptions;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if(!$this->mapDivId)throw new Exception('ERROR: Missing widget configuration. The property $mapDivId is not set. [ id of HTML element containing map. For example: ["mapDivId"=>"map"]]');
        $this->containerId =($this->containerId)?$this->containerId:'routing_container-'.$this->id;
        $this->userLocationDivId=($this->userLocationDivId)?$this->userLocationDivId:'routing_user_location-'.$this->id;
        $ghAsset=$this->getView()->registerAssetBundle('common\modules\routing\assets\GraphHopperRoutingAsset',View::POS_END);
        $widgetAsset=$this->getView()->registerAssetBundle('common\modules\routing\widgets\graphhopper\assets\GraphHopperRoutingWidgetAsset');

        $this->ghAssetBaseUrl=$ghAsset->baseUrl;
        $this->widgetAssetBaseUrl =$widgetAsset->baseUrl;

        $this->clientOptions['mapDivId']=$this->mapDivId;
        $this->clientOptions['ghAssetBaseUrl']=$this->ghAssetBaseUrl;
        $this->clientOptions['widgetAssetBaseUrl']=$this->widgetAssetBaseUrl;
        $this->clientOptions['containerId']=$this->containerId;
        $this->clientOptions['userLocationDivId']=$this->userLocationDivId;
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render(
            'routing-widget/view',
            [
                'clientOptions'=>$this->clientOptions,
                'containerId'=>$this->containerId,
            ]
        );
    }

}