<?php
/**
 * Created by PhpStorm.
 * User: girc
 * Date: 2/13/15
 * Time: 2:20 AM
 */

namespace common\modules\rapid_assessment\models;

use common\modules\rapid_assessment\models\query\ItemTypeQuery;

class ItemTypeIncident extends ItemType{
    const TYPE = ItemType::TYPE_INCIDENT;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->type=self::TYPE;
    }

    public static function find()
    {
        return new ItemTypeQuery(get_called_class(), ['type' => self::TYPE]);
    }
}