<?php

namespace common\modules\building_assessment\controllers;

use common\components\utils\php\ArrayHelper;
use common\modules\building_assessment\models\BuildingHousehold;
use common\modules\building_assessment\models\search\BuildingHouseholdSearch;
use ramshresh\yii2\galleryManager\GalleryManagerAction;
use Yii;
use yii\db\Transaction;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * CrudBuildingHouseholdController implements the CRUD actions for BuildingHousehold model.
 */
class CrudBuildingHouseholdController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all BuildingHousehold models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BuildingHouseholdSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single BuildingHousehold model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the BuildingHousehold model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return BuildingHousehold the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = BuildingHousehold::findOne($id)) !== null) {
            return $model;
        }else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Creates a new BuildingHousehold model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new BuildingHousehold();

        if ($model->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            if($model->save()){
                if (UploadedFile::getInstanceByName('photo')) {
                    $photoData = (Yii::$app->request->post('photo_data')) ? Yii::$app->request->post('photo_data') : null;
                    $model->getBehavior('galleryBehavior')->addUploadedImage('photo', $photoData);
                }
                $transaction->commit();
                return $this->redirect(['view', 'id' => $model->id]);
            }else{
                Yii::$app->session->setFlash('error', 'Error Saving Model');
                $transaction->rollBack();
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing BuildingHousehold model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing BuildingHousehold model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actions()
    {
        return ArrayHelper::merge(
            parent::actions(),
            [
                'galleryApi' => [
                    'class' => GalleryManagerAction::className(),
                    // mappings between type names and model classes (should be the same as in behaviour)
                    'types' => [
                        'building_household' => BuildingHousehold::className()
                    ]
                ]
            ]); // TODO: Change the autogenerated stub
    }

}
