<?php
/**
 * Created by PhpStorm.
 * User: girc
 * Date: 1/24/15
 * Time: 8:44 PM
 */

namespace common\modules\routing\assets;


use yii\web\AssetBundle;

class GraphHopperUtilAsset extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath=__DIR__."/graphhopper";
        $this->js=[
            'js/GHUtil.js',
        ];
    }


}