<?php

namespace api\modules\user\controllers;

use common\modules\user\models\forms\LoginForm;
use common\modules\user\models\User;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\rest\Controller;

class DefaultController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        header("Access-Control-Allow-Origin: *");
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'confirm', 'resend'],
                        'allow' => true,
                        'roles' => ['?', '@'],
                    ],
                    [
                        'actions' => ['account', 'profile', 'resend-change', 'cancel', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login', 'register', 'forgot', 'reset'],
                        'allow' => true,
                        'roles' => ['?','@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    // 'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return array_merge(parent::actions(), [
                'register' => [
                    'class' => 'common\modules\user\actions\RegisterAction',
                    'modelClass' => User::className(),
                ],
                'login' => [
                    'class' => 'common\modules\user\actions\LoginAction',
                    'modelClass' => LoginForm::className(),
                ],
                'logout' => [
                    'class' => 'common\modules\user\actions\LogoutAction',
                    'modelClass' => LoginForm::className(),
                ]
            ]
        );
    }
}
