<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 4/9/2015
 * Time: 3:38 PM
 */

namespace api\modules\user\controllers;

use common\modules\user\models\forms\LoginForm;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;


class UserController extends \yii\rest\ActiveController
{
    public $modelClass = 'common\modules\user\models\User';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        header("Access-Control-Allow-Origin: *");
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'confirm', 'resend'],
                        'allow' => true,
                        'roles' => ['?', '@'],
                    ],
                    [
                        'actions' => ['account', 'profile', 'resend-change', 'cancel', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login', 'register', 'forgot', 'reset'],
                        'allow' => true,
                        'roles' => ['?','@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    // 'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return array_merge(parent::actions(), [
                'register' => [
                    'class' => 'common\modules\user\actions\RegisterAction',
                    'modelClass' => $this->modelClass,
                ],
                'login' => [
                    'class' => 'common\modules\user\actions\LoginAction',
                    'modelClass' => LoginForm::className(),
                ],
                'logout' => [
                    'class' => 'common\modules\user\actions\LogoutAction',
                    'modelClass' => LoginForm::className(),
                ],
                'confirm' => [
                    'class' => 'common\modules\user\actions\confirmAction',
                ]
            ]
        );
    }
}