<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 4/1/2015
 * Time: 7:19 AM
 */

namespace common\modules\social_media\components;


use yii\base\Component;
use yii\data\SqlDataProvider;
use yii\db\Connection;
use yii\db\Query;
use yii\di\Instance;

class TwitterDbManager extends  Component{
    public $db='db';
    public $tweetTable="{{%social_media}}.{{%tweet}}";

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->db = Instance::ensure($this->db, Connection::className());
    }

    public function getMedia(){
        /*
         * "
         * SELECT
         *  media_url,tweets,date_utc::TIMESTAMP
         * FROM
         *  social_media.tweet
         * WHERE
         *  media_url is not Null
         * ORDER BY
         *  date_utc::TIMESTAMP DESC
         * LIMIT 30"
         */
        $rows = (new Query())->select('media_url,tweets,date_utc::TIMESTAMP')
            ->from([$this->tweetTable])
            ->where('media_url IS NOT NULL')
            ->orderBy('date_utc::TIMESTAMP DESC')
            ->limit(30)->all($this->db);
        return $rows === false ? null : $rows;
    }
}