<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 4/10/2015
 * Time: 4:48 AM
 */

namespace common\modules\user\actions;

use common\components\MyBaseAction;
use yii;

class LoginAction extends MyBaseAction
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * registration api action
     */
    public function run()
    {
        /** @var \common\modules\user\models\forms\LoginForm $model */
        // load post data and login
        $model = Yii::$app->getModule("user")->model("LoginForm");

        if ($model->load(Yii::$app->request->post()) && $model->login(Yii::$app->getModule("user")->loginDuration)) {
            $user = $model->getUser();
            echo yii\helpers\Json::encode(['status'=>'success','msg'=>'login success',"user"=>["id"=>$user->id,"username"=>$user->profile->full_name,"email"=>$user->email]]);
            Yii::$app->end();
            //$this->sendSuccessResponseOnAjaxFormSubmit('Login Successful',$user);
        }else {
            $this->sendErrorResponseOnAjaxFormSubmit([$model]);
        }

        // render
        return $this->render('login', [
            'model' => $model,
        ]);
    }


}