<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 4/10/2015
 * Time: 4:48 AM
 */

namespace common\modules\user\actions;

use common\components\MyBaseAction;
use common\modules\user\components\User;
use yii;

class LogoutAction extends MyBaseAction
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * registration api action
     */
    public function run()
    {
        Yii::$app->user->logout();
        $this->sendSuccessResponseOnAjaxFormSubmit('Logged Out');
    }
}