<?php
/**
 * Created by PhpStorm.
 * User: girc
 * Date: 1/24/15
 * Time: 7:08 PM
 */

namespace common\assets;

use yii\web\AssetBundle;

class OopJsAsset extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = __DIR__.'/oop-js';
        $this->js=['/simple-javascript-inheritance.js'];
    }
}