<?php
/**
 * Created by PhpStorm.
 * User: girc
 * Date: 1/24/15
 * Time: 7:08 PM
 */

namespace common\assets;

use yii\web\AssetBundle;

class YiiAjaxFormSubmitAsset extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath=__DIR__."/yii-ajax-form-submit";
        $this->js=[
            'js/yii-ajax-form-submit-widget.js',
        ];
       $this->depends = [
           'yii\web\JqueryAsset',
           'yii\web\YiiAsset',
           'yii\bootstrap\BootstrapAsset',
       ];
    }
}