<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 4/12/2015
 * Time: 9:40 AM
 */

namespace common\modules\user\controllers;

use yii;
use yii\web\Controller;
use yii\widgets\ActiveForm;
use yii\web\Response;
class AccountController extends Controller{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->defaultAction='account';
    }

    /**
     * Account
     */
    public function actionAccount()
    {
        /** @var \common\modules\user\models\User $user */
        /** @var \common\modules\user\models\UserKey $userKey */

        // set up user and load post data
        $user = Yii::$app->user->identity;
        $user->setScenario("account");
        $loadedPost = $user->load(Yii::$app->request->post());

        // validate for ajax request
        if ($loadedPost && Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($user);
        }

        // validate for normal request
        if ($loadedPost && $user->validate()) {

            // generate userKey and send email if user changed his email
            if (Yii::$app->getModule("user")->emailChangeConfirmation && $user->checkAndPrepEmailChange()) {

                $userKey = Yii::$app->getModule("user")->model("UserKey");
                $userKey = $userKey::generate($user->id, $userKey::TYPE_EMAIL_CHANGE);
                if (!$numSent = $user->sendEmailConfirmation($userKey)) {

                    // handle email error
                    //Yii::$app->session->setFlash("Email-error", "Failed to send email");
                }
            }

            // save, set flash, and refresh page
            $user->save(false);
            Yii::$app->session->setFlash("Account-success", Yii::t("user", "Account updated"));
            return $this->refresh();
        }

        // render
        return $this->render("account", [
            'user' => $user,
        ]);
    }
}