<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 4/12/2015
 * Time: 9:40 AM
 */

namespace common\modules\user\controllers;

use common\components\MyBaseContoller;
use yii;

class LoginController extends MyBaseContoller{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->defaultAction='login';
    }

    /**
     * Displays login Form
     */
    public function actionLogin(){
        /** @var \common\modules\user\models\forms\LoginForm $model */

        // load post data and login
        $model = Yii::$app->getModule("user")->model("LoginForm");
        if(Yii::$app->request->isAjax){
            if ($model->load(Yii::$app->request->post()) && $model->login(Yii::$app->getModule("user")->loginDuration)) {
                return $this->goBack(Yii::$app->getModule("user")->loginRedirect);
            }else{
                $this->sendErrorResponseOnAjaxFormSubmit([$model]);
            }
        }

        if ($model->load(Yii::$app->request->post()) && $model->login(Yii::$app->getModule("user")->loginDuration)) {
            return $this->goBack(Yii::$app->getModule("user")->loginRedirect);
        }

        // render
        return $this->render('login', [
            'model' => $model,
        ]);
    }
}