<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 4/12/2015
 * Time: 9:40 AM
 */

namespace common\modules\user\controllers;

use yii;
use yii\web\Controller;

class LogoutController extends Controller{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->defaultAction='logout';
    }

    /**
     * Log user out and redirect
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        // redirect
        $logoutRedirect = Yii::$app->getModule("user")->logoutRedirect;
        if ($logoutRedirect === null) {
            return $this->goHome();
        }
        else {
            return $this->redirect($logoutRedirect);
        }
    }
}