<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 4/12/2015
 * Time: 9:40 AM
 */

namespace common\modules\user\controllers;

use yii;
use yii\web\Controller;
use yii\widgets\ActiveForm;
use yii\web\Response;

class ProfileController extends Controller{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->defaultAction='profile';
    }

    /**
     * Profile
     */
    public function actionProfile()
    {

        /** @var \common\modules\user\models\Profile $profile */

        // set up profile and load post data
        $profile = Yii::$app->user->identity->profile;
        $loadedPost = $profile->load(Yii::$app->request->post());

        // validate for ajax request
        if ($loadedPost && Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($profile);
        }

        // validate for normal request
        if ($loadedPost && $profile->validate()) {
            $profile->save(false);
            Yii::$app->session->setFlash("Profile-success", Yii::t("user", "Profile updated"));
            return $this->refresh();
        }
        // render
        return $this->render("profile", [
            'profile' => $profile,
        ]);
    }
}